[package]
name = "let-kagi-read-private-repos"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Henderson <ethan@zbee.codes>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.8", features = ['http'] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.11.0"
hex = "0.4"
base64 = "0.23.1"
rand = "0.10.2"

[profile.release]
lto = true
opt-level = "s"